services:
  db:
    image: postgres:18.1-bookworm
    env_file:
      - path: ./.env
        required: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  back_end:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
  migrator:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: ["node", "./migrate.mjs"]
    env_file:
      - path: ./.env
        required: true
    depends_on:
      back_end:
        condition: service_healthy
    restart: "no"
